import type { PresetPattern } from "@/types";

export const PATTERN_PRESETS: PresetPattern[] = [
  // --- Spaceships ---
  {
    name: "Glider",
    category: "Spaceship",
    description: "The smallest spaceship; travels diagonally across the grid every 4 ticks.",
    grid: [
      [0, 1],
      [1, 2],
      [2, 0],
      [2, 1],
      [2, 2],
    ],
  },
  {
    name: "Lightweight Spaceship",
    category: "Spaceship",
    description: "Flies horizontally across the board with period 4 (speed c/2).",
    grid: [
      [0, 1],
      [0, 4],
      [1, 0],
      [2, 0],
      [2, 4],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
    ],
  },
  {
    name: "Middleweight Spaceship",
    category: "Spaceship",
    description: "Medium-sized orthogonal spaceship travelling at half the speed of light.",
    grid: [
      [0, 2],
      [1, 0],
      [1, 4],
      [2, 5],
      [3, 0],
      [3, 5],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
      [4, 5],
    ],
  },
  {
    name: "Heavyweight Spaceship",
    category: "Spaceship",
    description: "The largest of the standard trio of orthogonal spaceships.",
    grid: [
      [0, 2],
      [0, 3],
      [1, 0],
      [1, 5],
      [2, 6],
      [3, 0],
      [3, 6],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
      [4, 5],
      [4, 6],
    ],
  },

  // --- Guns ---
  {
    name: "Gosper Glider Gun",
    category: "Gun",
    description: "The first known gun; continuously creates gliders every 30 ticks.",
    grid: [
      [4, 0],
      [4, 1],
      [5, 0],
      [5, 1],
      [2, 12],
      [2, 13],
      [3, 11],
      [3, 15],
      [4, 10],
      [4, 16],
      [5, 10],
      [5, 14],
      [5, 16],
      [5, 17],
      [6, 10],
      [6, 16],
      [7, 11],
      [7, 15],
      [8, 12],
      [8, 13],
      [0, 24],
      [1, 22],
      [1, 24],
      [2, 20],
      [2, 21],
      [3, 20],
      [3, 21],
      [4, 20],
      [4, 21],
      [5, 22],
      [5, 24],
      [6, 24],
      [2, 34],
      [2, 35],
      [3, 34],
      [3, 35],
    ],
  },
  {
    name: "Simkin Glider Gun",
    category: "Gun",
    description: "Discovered in 2015; produces a glider every 120 generations.",
    grid: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
      [3, 4],
      [3, 5],
      [4, 4],
      [4, 5],
      [0, 7],
      [0, 8],
      [1, 7],
      [1, 8],
      [10, 21],
      [10, 22],
      [11, 20],
      [11, 23],
      [12, 20],
      [12, 24],
      [13, 20],
      [13, 24],
      [14, 21],
      [14, 22],
      [14, 23],
      [17, 26],
      [17, 27],
      [18, 26],
      [18, 27],
      [20, 30],
      [20, 31],
      [21, 30],
      [21, 31],
    ],
  },

  // --- Oscillators ---
  {
    name: "Blinker",
    category: "Oscillator",
    description: "Smallest period 2 oscillator; alternates horizontal and vertical.",
    grid: [
      [0, 0],
      [0, 1],
      [0, 2],
    ],
  },
  {
    name: "Toad",
    category: "Oscillator",
    description: "Period 2 oscillator composed of two parallel 3-cell bars.",
    grid: [
      [0, 1],
      [0, 2],
      [0, 3],
      [1, 0],
      [1, 1],
      [1, 2],
    ],
  },
  {
    name: "Beacon",
    category: "Oscillator",
    description: "Period 2 oscillator made of two touching diagonal blocks.",
    grid: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
      [2, 2],
      [2, 3],
      [3, 2],
      [3, 3],
    ],
  },
  {
    name: "Pulsar",
    category: "Oscillator",
    description: "Period 3 oscillator with an expansive symmetric pulse.",
    grid: [
      [1, 3],
      [1, 4],
      [1, 5],
      [1, 9],
      [1, 10],
      [1, 11],
      [3, 1],
      [3, 6],
      [3, 8],
      [3, 13],
      [4, 1],
      [4, 6],
      [4, 8],
      [4, 13],
      [5, 1],
      [5, 6],
      [5, 8],
      [5, 13],
      [6, 3],
      [6, 4],
      [6, 5],
      [6, 9],
      [6, 10],
      [6, 11],
      [8, 3],
      [8, 4],
      [8, 5],
      [8, 9],
      [8, 10],
      [8, 11],
      [9, 1],
      [9, 6],
      [9, 8],
      [9, 13],
      [10, 1],
      [10, 6],
      [10, 8],
      [10, 13],
      [11, 1],
      [11, 6],
      [11, 8],
      [11, 13],
      [13, 3],
      [13, 4],
      [13, 5],
      [13, 9],
      [13, 10],
      [13, 11],
    ],
  },
  {
    name: "Pentadecathlon",
    category: "Oscillator",
    description: "Period 15 oscillator capable of reflecting gliders.",
    grid: [
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [1, 5],
      [1, 6],
      [1, 7],
      [1, 8],
      [1, 9],
    ],
  },
  {
    name: "Figure Eight",
    category: "Oscillator",
    description: "Period 8 oscillator shaped like two interlocking 3x3 blocks.",
    grid: [
      [0, 0],
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 1],
      [1, 2],
      [2, 0],
      [2, 1],
      [2, 2],
      [3, 3],
      [3, 4],
      [3, 5],
      [4, 3],
      [4, 4],
      [4, 5],
      [5, 3],
      [5, 4],
      [5, 5],
    ],
  },
  {
    name: "Kok's Galaxy",
    category: "Oscillator",
    description: "Period 8 rotating spiral galaxy with 4 distinct arms.",
    grid: [
      [0, 0],
      [0, 1],
      [0, 2],
      [0, 3],
      [0, 4],
      [0, 5],
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [1, 5],
      [0, 7],
      [0, 8],
      [1, 7],
      [1, 8],
      [2, 7],
      [2, 8],
      [3, 7],
      [3, 8],
      [4, 7],
      [4, 8],
      [5, 7],
      [5, 8],
      [7, 3],
      [7, 4],
      [7, 5],
      [7, 6],
      [7, 7],
      [7, 8],
      [8, 3],
      [8, 4],
      [8, 5],
      [8, 6],
      [8, 7],
      [8, 8],
      [3, 0],
      [3, 1],
      [4, 0],
      [4, 1],
      [5, 0],
      [5, 1],
      [6, 0],
      [6, 1],
      [7, 0],
      [7, 1],
      [8, 0],
      [8, 1],
    ],
  },
  {
    name: "Octagon II",
    category: "Oscillator",
    description: "Period 5 circular oscillator with hypnotic pulsing symmetry.",
    grid: [
      [0, 3],
      [0, 4],
      [1, 2],
      [1, 5],
      [2, 1],
      [2, 6],
      [3, 0],
      [3, 7],
      [4, 0],
      [4, 7],
      [5, 1],
      [5, 6],
      [6, 2],
      [6, 5],
      [7, 3],
      [7, 4],
    ],
  },

  // --- Still Lifes ---
  {
    name: "Block",
    category: "Still Life",
    description: "The simplest 2x2 stable still life pattern.",
    grid: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
    ],
  },
  {
    name: "Beehive",
    category: "Still Life",
    description: "The second most common stable still life in Game of Life.",
    grid: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 2],
    ],
  },
  {
    name: "Loaf",
    category: "Still Life",
    description: "A 7-cell asymmetric still life resembling a loaf of bread.",
    grid: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 3],
      [3, 2],
    ],
  },
  {
    name: "Boat",
    category: "Still Life",
    description: "A 5-cell still life with diagonal symmetry.",
    grid: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
    ],
  },
  {
    name: "Tub",
    category: "Still Life",
    description: "A 4-cell hollow still life with diagonal reflection symmetry.",
    grid: [
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
    ],
  },
  {
    name: "Eater 1",
    category: "Still Life",
    description: "Classic fishhook still life that can consume oncoming gliders.",
    grid: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 2],
      [3, 2],
      [3, 3],
    ],
  },

  // --- Methuselahs ---
  {
    name: "Acorn",
    category: "Methuselah",
    description: "Takes 5,206 generations to stabilize and spawns 13 gliders.",
    grid: [
      [0, 1],
      [1, 3],
      [2, 0],
      [2, 1],
      [2, 4],
      [2, 5],
      [2, 6],
    ],
  },
  {
    name: "R-pentomino",
    category: "Methuselah",
    description: "Only 5 cells, yet evolves for 1,103 generations creating 6 gliders.",
    grid: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 1],
      [2, 1],
    ],
  },
  {
    name: "Diehard",
    category: "Methuselah",
    description: "Eventually vanishes completely after exactly 130 generations.",
    grid: [
      [0, 6],
      [1, 0],
      [1, 1],
      [2, 1],
      [2, 5],
      [2, 6],
      [2, 7],
    ],
  },
  {
    name: "B-heptomino",
    category: "Methuselah",
    description: "A 7-cell methuselah that creates an active reaction for 148 ticks.",
    grid: [
      [0, 1],
      [0, 2],
      [0, 3],
      [1, 0],
      [1, 1],
      [1, 2],
      [2, 1],
    ],
  },
  {
    name: "Pi-heptomino",
    category: "Methuselah",
    description: "Resembles Greek letter Pi; evolves dynamically for 173 generations.",
    grid: [
      [0, 0],
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 2],
      [2, 0],
      [2, 2],
    ],
  },
];

export const SPEED_PRESETS = [
  { label: "Slow (500ms)", ms: 500 },
  { label: "Medium (250ms)", ms: 250 },
  { label: "Fast (100ms)", ms: 100 },
  { label: "Hyper (40ms)", ms: 40 },
] as const;
