import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Conway’s Game of Life",
  description: "Dive into the mesmerizing world of Conway's Game of Life! Experience the magic of simple rules creating captivating patterns in this classic cellular automaton simulation. Explore the beauty of algorithmic evolution and enjoy the ever-changing landscapes generated by the game. Discover the simplicity behind the complexity of Life itself.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
