import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";

const tiny5 = localFont({
  src: "./Tiny5-Regular.ttf",
  variable: "--font-pixel",
  display: "swap",
});

export const viewport: Viewport = {
  themeColor: "#292929",
  width: "device-width",
  initialScale: 1,
};

const appDescription =
  "Dive into the mesmerizing world of Conway's Game of Life! Experience the magic of simple rules " +
  "creating captivating patterns in this classic cellular automaton simulation. " +
  "Explore the beauty of algorithmic evolution and enjoy the ever-changing landscapes generated by the game. " +
  "Discover the simplicity behind the complexity of Life itself.";

export const metadata: Metadata = {
  metadataBase: new URL("https://conway-game-of-life.souldev.me"),
  title: "Conway’s Game of Life",
  description: appDescription,
  keywords: [
    "Conway's Game of Life",
    "Cellular Automaton",
    "Game of Life Simulation",
    "John Conway",
    "Zero-Player Game",
    "Glider Gun",
    "Interactive Canvas",
    "Next.js Simulation",
    "React 19 Game of Life",
  ],
  authors: [{ name: "SoulDev07", url: "https://github.com/SoulDev07" }],
  creator: "SoulDev07",
  publisher: "SoulDev07",
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://conway-game-of-life.souldev.me/",
    siteName: "Conway’s Game of Life",
    title: "Conway’s Game of Life",
    description: appDescription,
    images: [
      {
        url: "/opengraph.png",
        width: 1200,
        height: 630,
        alt: "Conway’s Game of Life Simulation",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Conway’s Game of Life",
    description: appDescription,
    images: ["/opengraph.png"],
  },
  alternates: {
    canonical: "https://conway-game-of-life.souldev.me/",
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Conway's Game of Life",
  url: "https://conway-game-of-life.souldev.me/",
  description: appDescription,
  applicationCategory: "SimulationGame",
  operatingSystem: "Any",
  author: {
    "@type": "Person",
    name: "SoulDev07",
    url: "https://github.com/SoulDev07",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={tiny5.variable}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className={tiny5.className}>{children}</body>
    </html>
  );
}
